version: '3'
services:
  nginx:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .

    # Mapping of container port to host
    
    ports:
      - 127.0.0.1:8000:80 
      # - target: 80
      #   host_ip: 127.0.0.1
      #   published: "8000"
      #   protocol: tcp
      #   mode: host

    
