apiVersion: v1
kind: Service
metadata:
  name: jenkins-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: nginx
  type: NodePort #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 3000 #Service port
    targetPort: 80 #The port for the React.js application container
